In [1]:
import torch

In [11]:
x = torch.Tensor([5,3])
y = torch.Tensor([2,4])

print(x*y)

tensor([10., 12.])


In [6]:
x = torch.zeros([2,5])
print(x)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


In [12]:
x = torch.rand([2,5])
print(x)

tensor([[0.6583, 0.7184, 0.9857, 0.8951, 0.3930],
        [0.1270, 0.7625, 0.8046, 0.9713, 0.1710]])


In [14]:
x = x.view([1,10])
print(x)

tensor([[0.6583, 0.7184, 0.9857, 0.8951, 0.3930, 0.1270, 0.7625, 0.8046, 0.9713,
         0.1710]])
