In [1]:
import numpy as np

In [2]:
x = np.arange(1,100)

In [3]:
x = x**2
print(x)

[   1    4    9   16   25   36   49   64   81  100  121  144  169  196
  225  256  289  324  361  400  441  484  529  576  625  676  729  784
  841  900  961 1024 1089 1156 1225 1296 1369 1444 1521 1600 1681 1764
 1849 1936 2025 2116 2209 2304 2401 2500 2601 2704 2809 2916 3025 3136
 3249 3364 3481 3600 3721 3844 3969 4096 4225 4356 4489 4624 4761 4900
 5041 5184 5329 5476 5625 5776 5929 6084 6241 6400 6561 6724 6889 7056
 7225 7396 7569 7744 7921 8100 8281 8464 8649 8836 9025 9216 9409 9604
 9801]


In [4]:
x%2==0

array([False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False])

In [5]:
x[x%2==0]

array([   4,   16,   36,   64,  100,  144,  196,  256,  324,  400,  484,
        576,  676,  784,  900, 1024, 1156, 1296, 1444, 1600, 1764, 1936,
       2116, 2304, 2500, 2704, 2916, 3136, 3364, 3600, 3844, 4096, 4356,
       4624, 4900, 5184, 5476, 5776, 6084, 6400, 6724, 7056, 7396, 7744,
       8100, 8464, 8836, 9216, 9604])

In [6]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

In [7]:
print(arr[1][1])
print(arr[1,1])

5
5


In [8]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim) 

0
1
2
3


In [9]:
arr2 = np.array([1, 2, 3, 4], ndmin=5)

print(arr2)

[[[[[1 2 3 4]]]]]


In [10]:
arr3 = np.array([1,2,3,4,5, 2**60/2], dtype="int64")

In [11]:
arr3.nbytes

48

In [12]:
arr3.astype(float)

array([1.00000000e+00, 2.00000000e+00, 3.00000000e+00, 4.00000000e+00,
       5.00000000e+00, 5.76460752e+17])

In [13]:
print(arr3.base)

None


In [14]:
arr4 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr4.reshape(4, 3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [15]:
arr5 = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr5.reshape(-1)

print(newarr)

[1 2 3 4 5 6]


In [16]:
from time import time

In [17]:
start = time()
test1 = [i for i in range(1000000)]
print(time()-start)
del test1

0.07099413871765137


In [18]:
start = time()
test1 = np.arange(1000000)
print(time()-start)
del test1

0.0051021575927734375


In [19]:
test1 = [i for i in range(1000000)]
start = time()
for i in range(1000000):
    test1[i] += 10
print(time()-start)
del test1

0.16389989852905273


In [20]:
test1 = np.arange(1000000)
start = time()
test1 += 10
print(time()-start)
del test1

0.0025663375854492188


In [21]:
np.where(arr%2==0)

(array([0, 1, 1]), array([1, 0, 2]))

In [22]:
arr6 = np.array([1, 3, 5, 7])

x = np.searchsorted(arr6, [2, 4, 6])
print(x)

[1 2 3]


In [23]:
np.random.randint(100, size=(1000))

array([92, 79,  1, 86, 64, 28, 64, 27, 49, 58, 38, 93, 68, 91, 93, 42, 92,
       23, 71, 45, 30, 36, 17, 30, 92, 65, 38, 60, 47, 67,  6, 62, 39, 72,
       88, 19, 12, 97, 65, 57, 63, 34, 36, 42, 52, 65, 80, 69, 85, 72, 64,
       25, 51, 80, 30, 32, 55, 33, 32,  2, 58, 96, 91, 56, 32, 90, 43, 81,
       14, 28, 62, 95, 74, 52, 64, 14, 25, 10, 50, 77, 78, 10, 53, 96, 63,
       76, 42, 11, 68, 58, 40, 81, 43, 58, 31, 86, 40, 19, 87, 79, 57, 67,
       91, 12, 50, 15, 30, 85, 77, 80, 41, 79, 77, 11, 99,  8, 60, 47, 65,
        2, 16, 15, 68, 28, 80, 55, 86, 38, 31, 79, 75, 93, 99, 34, 75, 32,
       30, 52, 54, 17,  5, 84, 91,  1, 98, 79, 33, 98, 65, 56, 76, 47, 47,
       35, 81, 57,  0, 75, 24, 70, 75, 39, 11, 40, 59, 51, 80, 91, 29, 37,
        1, 18, 39, 76, 12, 38, 57, 74, 29, 48, 75, 10, 47, 57, 21, 14,  9,
       77, 72, 42, 96, 37, 29, 66, 41, 71, 13, 97, 72, 91, 30, 18, 68, 15,
       78, 38, 78, 37, 63, 27, 12,  5, 98, 77, 58, 18, 31, 43, 63, 12, 66,
       62, 74, 63, 37, 25

In [24]:
np.random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.6, 0.0], size=(100))

array([5, 5, 5, 7, 7, 3, 5, 5, 5, 5, 7, 5, 5, 5, 7, 7, 7, 7, 5, 7, 3, 3,
       7, 5, 7, 7, 5, 5, 5, 7, 5, 7, 3, 5, 5, 5, 7, 5, 7, 3, 7, 3, 7, 7,
       5, 7, 7, 5, 7, 5, 7, 7, 7, 7, 5, 7, 7, 7, 5, 3, 7, 5, 5, 5, 5, 7,
       7, 7, 7, 7, 7, 5, 7, 7, 7, 7, 7, 7, 7, 3, 7, 5, 7, 3, 3, 7, 7, 7,
       3, 7, 5, 7, 5, 7, 5, 7, 7, 5, 5, 3])

In [25]:
np.random.permutation([1,2,3,3,3,3,3,3,3])

array([3, 3, 3, 3, 1, 2, 3, 3, 3])

In [26]:
x = [1, 2, 3, 4]
y = [4, 5, 6, 7]
print(np.add(x, y))

[ 5  7  9 11]
