# Importing Numpy

In [29]:
import numpy as np
import math

# Simple arrays

In [30]:
arr = np.array([1,2,3,4])
print(arr)

print()

arr2d = np.array([[1, 2], [3, 4]]) 
print(arr2d)

[1 2 3 4]

[[1 2]
 [3 4]]


## ndim

In [31]:
arr = np.array([1, 2, 3, 4, 5], ndmin = 1) 
print(arr)

arr = np.array([1, 2, 3, 4, 5], ndmin = 2) 
print(arr)

arr = np.array([1, 2, 3, 4, 5], ndmin = 3) 
print(arr)

[1 2 3 4 5]
[[1 2 3 4 5]]
[[[1 2 3 4 5]]]


## dtype
All types https://www.tutorialspoint.com/numpy/numpy_data_types.htm

In [32]:
arr = np.array([1, 2, 3, 4, 5], dtype=np.int8)
print(arr)

arr = np.array([1, 2, 3, 4, 5], dtype=np.float16)
print(arr)

arr = np.array([0, 1, 2, 3, 4, 5], dtype=np.bool)
print(arr)

student = np.dtype([('name','S20'), ('age', 'i1'), ('marks', 'f4')]) 
arr = np.array([('abc', 21, 50),('xyz', 18, 75)], dtype = student) 
print(arr)
print(arr['name'])

[1 2 3 4 5]
[1. 2. 3. 4. 5.]
[False  True  True  True  True  True]
[(b'abc', 21, 50.) (b'xyz', 18, 75.)]
[b'abc' b'xyz']


# Array Attributes

## shapes

In [33]:
arr = np.array([[1,2,3],[4,5,6]])

print(arr.shape)
print(arr)

arr.reshape((3,2))

(2, 3)
[[1 2 3]
 [4 5 6]]


array([[1, 2],
       [3, 4],
       [5, 6]])

In [34]:
arr = np.arange(24)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [35]:
print(arr.reshape(3,2,4))
print()
print(arr.reshape(2,4,3))
print()
print(arr.reshape(12,2))
print()
print(arr)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]]]

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


## Sizes

In [36]:
print(arr.itemsize) # in bytes, depends on dtype
print(arr.nbytes)
print(arr.size)

8
192
24


## Other

In [37]:
x = np.zeros((6, 2), dtype = int) 
print(x)

x = np.ones((6, 2), dtype = int) 
print(x)

[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]]
[[1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]]


# Aranging

In [38]:
x = np.arange(5)
print(x)

x = np.arange(5, dtype=float)
print(x)

x = np.arange(10,20,2)
print(x)

x = np.arange(10,10.1,0.01)
print(x)

x = np.linspace(10,20,5, retstep=True) # Perfectly spaced
print(x)

x = np.logspace(1, 10, num=10, base=2) 
print(x)

[0 1 2 3 4]
[0. 1. 2. 3. 4.]
[10 12 14 16 18]
[10.   10.01 10.02 10.03 10.04 10.05 10.06 10.07 10.08 10.09]
(array([10. , 12.5, 15. , 17.5, 20. ]), 2.5)
[   2.    4.    8.   16.   32.   64.  128.  256.  512. 1024.]


# Boolean Array Indexing

In [39]:
x = np.array([[0, 1, 2],[3, 4, 5],[6, 7, 8],[9, 10, 11]])
print(x[x > 5])

[ 6  7  8  9 10 11]


## Slicing

In [40]:
a = np.array([[1,2,3],[3,4,5],[4,5,6]]) 

# this returns array of items in the second column 
print('The items in the second column are:')
print(a[...,1])
print()

# Now we will slice all items from the second row 
print('The items in the second row are:')
print(a[1,...])
print()

# Now we will slice all items from column 1 onwards 
print('The items column 1 onwards are:')
print(a[...,1:])

The items in the second column are:
[2 4 5]

The items in the second row are:
[3 4 5]

The items column 1 onwards are:
[[2 3]
 [4 5]
 [5 6]]


# Operations

In [45]:
a = np.array([[1,2,3],[3,4,5],[4,5,6]])
print(a + 10)
print(a * 20)
print(a // 20)
print(a**2)
print(a%2)
print(a%2==0)

[[11 12 13]
 [13 14 15]
 [14 15 16]]
[[ 20  40  60]
 [ 60  80 100]
 [ 80 100 120]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[ 1  4  9]
 [ 9 16 25]
 [16 25 36]]
[[1 0 1]
 [1 0 1]
 [0 1 0]]
[[False  True False]
 [False  True False]
 [ True False  True]]


# Iterating

In [49]:
a = np.array([[1,2,3],[3,4,5],[4,5,6]])
for i in np.nditer(a):
    print(i, end=" ")
print()

for i, j in np.nditer([a, [1,2,3]]):
    print(i,j)

1 2 3 3 4 5 4 5 6 
1 1
2 2
3 3
3 1
4 2
5 3
4 1
5 2
6 3


# Rounding

In [50]:
a = np.array([1.0,5.55, 123, 0.567, 25.532]) 

print(np.around(a))
print(np.around(a, decimals = 1))
print(np.around(a, decimals = -1))

[  1.   6. 123.   1.  26.]
[  1.    5.6 123.    0.6  25.5]
[  0.  10. 120.   0.  30.]
